name: karaca_katalog
description: Karaca-Prototype

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  firebase_core: ^1.21.1

  firebase_auth: ^3.7.0

  flutter_barcode_scanner: ^2.0.0

  barcode_widget:

  http: ^0.13.5

  carousel_slider: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/karaca_logo.png


